### ISSUE TITLE
自部署，申请开通跨域白名单权限

### ISSUE THREAD

**Issue by 80imike** [GSQZ/TuneFree#11]
需申请的域名：music.666666.dev

@GSQZ 麻烦大佬有空开通下，谢谢

**Comment by GSQZ** [comment]
已开

**Comment by 80imike** [comment]
> 已开

大佬，没有开成功的样子，是不是域名输错了？
烦请大佬在检查下哟 

@GSQZ 

<img width="1484" alt="image" src="https://github.com/GSQZ/TuneFree/assets/1665201/6988774a-e667-45ea-8a47-fe4d3b31d49a">

**Comment by GSQZ** [comment]
试试现在好了吗，昨天复制错域名了，抱歉

**Comment by 80imike** [comment]
> 试试现在好了吗，昨天复制错域名了，抱歉

之前可以了，现在又不行了，帮忙看看吧


<img width="1495" alt="image" src="https://github.com/GSQZ/TuneFree/assets/1665201/4b6a1ce1-3b57-4da3-9f92-98ddb9d30884">
