### ISSUE TITLE
自部署又不能正常播放音乐了，又出现跨域访问没权限问题？

### ISSUE THREAD

**Issue by 80imike** [GSQZ/TuneFree#20]
<img width="1480" alt="image" src="https://github.com/user-attachments/assets/2f2e3e08-415c-4b1a-a148-3c4fea0216da">

 https://cloud.wujiyan.cc/f/NqEIY/tunefree.mp3  这个域是大佬是新增加的，我看和之前的不一样

求个白名单权限

需开的白名单的两个域名：

music.666666.dev
music.bestgeek.org

@GSQZ  感谢大佬

**Comment by GSQZ** [comment]
接口自用了。服务器实在是承受不住了，后续想自部署的话需要自己更改一下解析接口
