### ISSUE TITLE
自部署 web 版本后，扫码登录的二维码显示不完整？

### ISSUE THREAD

**Issue by 80imike** [GSQZ/TuneFree#4]
自部署 web 版本后，扫码登录的二维码显示不完整？

<img width="641" alt="image" src="https://github.com/GSQZ/TuneFree/assets/1665201/e784bac9-4cc4-446e-acdc-b6e0b251fc26">

而用 splayer 部署的是可以正常显示的

<img width="867" alt="image" src="https://github.com/GSQZ/TuneFree/assets/1665201/1d0097a0-7829-45de-be6d-13f794d8b355">

大佬有时间看看吧 @GSQZ

**Comment by GSQZ** [comment]
已修复，最新代码已上传
