### ISSUE TITLE
win端窗口的最小化 全屏和关闭按钮消失

### ISSUE THREAD

**Issue by snouker** [GSQZ/TuneFree#7]
如图:
![image](https://github.com/GSQZ/TuneFree/assets/47094070/c24378ba-c3f8-43d3-af81-cbe55b455689)

临时解决方案:
 - 目前的解决方案是 ctrl+shift+i呼出控制台再关掉控制台
 - 任务栏右击图标,关闭窗口

**Comment by GSQZ** [comment]
点一下搜索框就可以了
